User ->>+ Browser: "Log in (username, password)"
Browser ->>+ ServiceProvider: "GET login page (username, password)"
ServiceProvider -->>- Browser: "200 authenticated successfully"
Browser -->>- User: "Logged in"
User ->>+ Browser: "Please remove rights from this consumer."
Browser ->>+ ServiceProvider: "GET remove access from <consumer>"
ServiceProvider -->>- Browser: "200 Token revoked"
Browser -->>- User: "Token revoked"
Consumer ->>+ ServiceProvider: "GET username (consumer_key,access_token,signature)"
ServiceProvider -->>- Consumer: "401 (unauthorized)"
