
# Warning: This file is edited by hand. Don't overwrite it!
#   (Although there's always Git.)

participant User
participant Browser
participant Consumer
participant OAuthHub
participant ServiceProvider

opt "Beforehand"
    OAuthHub ->>+ ServiceProvider: "register as a Consumer"
    ServiceProvider -->>- OAuthHub: "Consumer key & secret"
    Consumer ->>+ OAuthHub: "register as a Consumer"
    OAuthHub -->>- Consumer: "Consumer key & secret"
end

User ->>+ Browser: "navigate to Consumer website"
Browser ->>+ Consumer: "GET /"
Consumer -->>- Browser: "200"
Browser -->>- User: "('Sign In via OAuthHub')"

opt "OAuth between Consumer and OAuthHub"
    User ->>+ Browser: "click 'Sign In via OAuthHub' button"
    Browser ->>+ Consumer: "GET /some_login_form"
    Consumer ->>+ OAuthHub: "GET /request_token {Consumer's callback}"
    OAuthHub -->>- Consumer: "200 {RT & RTS}"
    Consumer -->>- Browser: "302 <OAuthHub>/authorize_url {RT}"
    Browser ->>+ OAuthHub: "GET <302'd>"

    alt "if User isn't signed in to OAuthHub: OAuth between OAuthHub and ServiceProvider"
        OAuthHub -->>- Browser: "200"
        Browser -->>- User: "('Sign in with Twitter')"
        User ->>+ Browser: "(clicks 'Sign in with Twitter')"
        Browser ->>+ OAuthHub: "POST /some_login_submit {login credentials}"
        OAuthHub ->>+ ServiceProvider: "GET /request_token {OAuthHub's callback}"
        ServiceProvider -->>- OAuthHub: "200 {RT & RTS}"
        OAuthHub -->>- Browser: "302 <ServiceProvider>/authorize_url {RT}"
        Browser ->>+ ServiceProvider: "GET <302'd>"

        alt "if User isn't signed in to Twitter: credential sign-in"
            ServiceProvider -->>- Browser: "200"
            Browser -->>- User: "(username-password form)"
            User ->>+ Browser: "(provides credentials, clicks submit)"
            Browser ->>+ ServiceProvider: "POST /some_login/ {credentials}"
        end
        ServiceProvider -->>- Browser: "200"
        Browser -->>- User: "('Grant OAuthHub access to <...>?')"

        User ->>+ Browser: "(Clicks 'yes')"
        Browser ->>+ ServiceProvider: "POST /some_callback/ {'yes'}"
        ServiceProvider -->>- Browser: "302 <oah-callback> {oauth verifier}"
        Browser ->>+ OAuthHub: "GET <302'd>"
        OAuthHub ->>+ ServiceProvider: "GET /access_token {RT & RTS}"
        ServiceProvider -->>- OAuthHub: "200 {AT & ATS}"
    end
    OAuthHub -->>- Browser: "200"
    Browser -->>- User: "('Logged in to <...>, authorize <...>?')"

    User ->>+ Browser: "(clicked 'yes')"
    Browser ->>+ OAuthHub: "POST /some_callback/ {'yes'}"
    OAuthHub -->>- Browser: "302 http://consumer.com {oauth verifier}"
    Browser ->>+ Consumer: "GET <302'd>"
    Consumer ->>+ OAuthHub: "POST /access_token {RT & RTS}"
    OAuthHub -->>- Consumer: "200 {AT & ATS}"
    #note right of Consumer
    #    Now the Consumer associates the access token/secret
    #    with the User session (cookies)
    #end note
    Consumer -->>- Browser: "200"
    Browser -->>- User: "('log-in sucess')"
end

#opt "Business logic"
#    Consumer ->>+ ServiceProvider: "GET username (consumer_key, access_token, signature)"
#    ServiceProvider -->>- Consumer: "200 (username)"
#end
#
#opt "Revocation"
#    User ->>+ Browser: "Log in (username, password)"
#    Browser ->>+ ServiceProvider: "GET login page (username, password)"
#    ServiceProvider -->>- Browser: "200 authenticated successfully"
#    Browser -->>- User: "Logged in"
#    User ->>+ Browser: "Please remove rights from this consumer."
#    Browser ->>+ ServiceProvider: "GET remove access from <consumer>"
#    ServiceProvider -->>- Browser: "200 Token revoked"
#    Browser -->>- User: "Token revoked"
#    Consumer ->>+ ServiceProvider: "GET username (consumer_key,access_token,signature)"
#    ServiceProvider -->>- Consumer: "401 (unauthorized)"
#end
